=== tarunasri/EclipseCode/3may2017 eclipse code/upsmodelling/resources/html/defaultsToNewUsers/panelmenubar.dtd
<!ELEMENT PANELMENUBAR ( DOUBLECLICK*, MENU+ )>
<!ATTLIST PANELMENUBAR name CDATA #REQUIRED>

<!ELEMENT DOUBLECLICK EMPTY >
<!ATTLIST DOUBLECLICK name CDATA #IMPLIED >
<!ATTLIST DOUBLECLICK action_type NMTOKEN #IMPLIED >
<!ATTLIST DOUBLECLICK action_value CDATA #IMPLIED>
<!ATTLIST DOUBLECLICK action_command CDATA #IMPLIED>


<!ELEMENT MENU ( DOUBLECLICK*, MENU-ITEM* ,MENU-ITEM-GROUP*,MENU-ITEM* ) >
<!ATTLIST MENU name CDATA #REQUIRED>
<!ATTLIST MENU owner  CDATA #IMPLIED>
<!ATTLIST MENU group CDATA #IMPLIED>
<!ATTLIST MENU shortcut_key CDATA #IMPLIED>
<!ATTLIST MENU position CDATA #IMPLIED>
<!ATTLIST MENU menutype CDATA #IMPLIED>
<!ATTLIST MENU menufile CDATA #IMPLIED>

<!ELEMENT MENU-ITEM-GROUP (OPERATION*, MENU-ITEM+) >
<!ATTLIST MENU-ITEM-GROUP name CDATA #REQUIRED>

<!ELEMENT MENU-ITEM ( HTML-UI | JAVA-UI | OPERATION )* >
<!ATTLIST MENU-ITEM ACTION-ON-NO-PRIVILEGE NMTOKEN #IMPLIED >

<!ATTLIST MENU-ITEM name CDATA #REQUIRED>
<!ATTLIST MENU-ITEM action_type  CDATA #IMPLIED>
<!ATTLIST MENU-ITEM action_value CDATA #IMPLIED>
<!ATTLIST MENU-ITEM accelerator_key CDATA #IMPLIED>
<!ATTLIST MENU-ITEM accelerator_modifier CDATA #IMPLIED>
<!ATTLIST MENU-ITEM shortcut_key CDATA #IMPLIED>
<!ATTLIST MENU-ITEM action_command CDATA  #IMPLIED>

<!ELEMENT HTML-UI EMPTY>
<!ATTLIST HTML-UI action_type  CDATA #IMPLIED>
<!ATTLIST HTML-UI action_value  CDATA #IMPLIED>
<!ATTLIST HTML-UI action_command CDATA #IMPLIED>
<!ATTLIST HTML-UI action_link CDATA #IMPLIED>
<!ATTLIST HTML-UI target CDATA #IMPLIED>

<!ELEMENT JAVA-UI EMPTY>
<!ATTLIST JAVA-UI name  CDATA  #IMPLIED>
<!ATTLIST JAVA-UI action_type  CDATA  #IMPLIED>
<!ATTLIST JAVA-UI action_value  CDATA  #IMPLIED>
<!ATTLIST JAVA-UI action_command CDATA #IMPLIED>
<!ATTLIST JAVA-UI shortcut_key CDATA #IMPLIED>
<!ATTLIST JAVA-UI accelerator_modifier CDATA #IMPLIED>
<!ATTLIST JAVA-UI accelerator_key CDATA #IMPLIED>

<!ELEMENT OPERATION EMPTY>
<!ATTLIST OPERATION name CDATA #REQUIRED>

=== tarunasri/EclipseCode/2june2017 eclipse code/upsmodelling/resources/html/defaultsToNewUsers/TreeOperations.xml
<!DOCTYPE PANELMENUBAR SYSTEM "panelmenubar.dtd">
<!--/$Id: TreeOperations.xml,v 1.2 2008/12/08 13:40:58 johnpaul Exp $-->
<PANELMENUBAR name="FRAMEMENU">
<MENU name = "Node Operations">
      
                <MENU-ITEM name = "Add Node">
                        <JAVA-UI
                               action_type="openframe"
                               action_value="com.adventnet.nms.util.ModifyTreeNode?Operation=Add"
                               
                               shortcut_key = "N"
			       accelerator_modifier="CNTRL-SHIFT"
			       accelerator_key="N">
                        </JAVA-UI>
                </MENU-ITEM>
                <MENU-ITEM name = "Modify Node">
                        <JAVA-UI
                        action_type="openframe"
                        action_value="com.adventnet.nms.util.ModifyTreeNode?Operation=Modify"
                        shortcut_key = "F"
			accelerator_modifier="CNTRL-SHIFT"
			accelerator_key="Y">
                        </JAVA-UI>
                </MENU-ITEM> 
                <MENU-ITEM name = "Delete Node">
                        <JAVA-UI
                        action_type="openframe"
                        action_value="com.adventnet.nms.util.ModifyTreeNode?Operation=Delete"
                        shortcut_key = "L"
                        accelerator_modifier="CNTRL-SHIFT"
			accelerator_key="X">
                        </JAVA-UI>
                </MENU-ITEM>
                <MENU-ITEM name = "Move Node">
                        <JAVA-UI
                        action_type="openframe"
                        action_value="com.adventnet.nms.util.ModifyTreeNode?Operation=Move"
                        shortcut_key = "V"
                        accelerator_modifier="CNTRL-SHIFT"
			accelerator_key="V">
                        
                        </JAVA-UI>
                </MENU-ITEM> 
</MENU>
</PANELMENUBAR>
